#!/usr/bin/env bash
#
# extract.sh -- unpack Simulink-generated ROS code into this package.
#
# Looks for ../<package>.tgz (where <package> is the name of the folder that
# contains scripts/), and extracts its contents into this folder, overwriting
# any files that are already here.
#
# The one exception is a README: this package's README.md is never
# overwritten. A README found in the archive is saved next to it with
# ".generated" added to its name (README.md -> README.generated.md).
#
# Usage:
#   ./scripts/extract.sh                 # uses ../<package>.tgz
#   ./scripts/extract.sh path/to/x.tgz   # uses a different archive

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PKG_NAME="$(basename "$PKG_DIR")"
TGZ="${1:-$PKG_DIR/../$PKG_NAME.tgz}"

if [ ! -f "$TGZ" ]; then
    echo "error: archive not found: $TGZ" >&2
    echo "Copy $PKG_NAME.tgz (generated by Simulink) into $(dirname "$PKG_DIR")/ and try again." >&2
    exit 1
fi

# Every entry must live under "<package>/" -- refuse anything else (including
# absolute paths and "..") rather than write outside this folder.
if tar -tzf "$TGZ" | grep -v -E "^(\./)?$PKG_NAME(/|$)" | grep -q .; then
    echo "error: $TGZ contains files outside a top-level '$PKG_NAME/' folder." >&2
    echo "Is this the archive generated from the $PKG_NAME Simulink model?" >&2
    exit 1
fi
if tar -tzf "$TGZ" | grep -q -E '(^|/)\.\.(/|$)'; then
    echo "error: $TGZ contains '..' path entries; refusing to extract." >&2
    exit 1
fi

STAGE="$(mktemp -d "${TMPDIR:-/tmp}/$PKG_NAME.XXXXXX")"
trap 'rm -rf "$STAGE"' EXIT

echo "Extracting $TGZ"
tar -xzf "$TGZ" -C "$STAGE"
SRC="$STAGE/$PKG_NAME"
# Some generated files are read-only; make them writable so a later
# extraction can overwrite them.
chmod -R u+w "$SRC"

# Keep our README.md: rename any top-level README from the archive.
for f in "$SRC"/README "$SRC"/README.* "$SRC"/readme "$SRC"/readme.*; do
    [ -f "$f" ] || continue
    base="$(basename "$f")"
    case "$base" in
        *.*) new="${base%.*}.generated.${base##*.}" ;;
        *)   new="$base.generated" ;;
    esac
    mv "$f" "$SRC/$new"
    echo "  archive $base saved as $new (your README.md is unchanged)"
done

# Copy everything into this package, overwriting existing files.
cp -Rf "$SRC"/. "$PKG_DIR"/

echo "Done. Files from $(basename "$TGZ") are now in $PKG_DIR"
echo "Next: rebuild the workspace (catkin_make), or just use ./scripts/run.sh from rossim/."
